### ISSUE TITLE
komaletter output cannot be rendered on Windows

### ISSUE THREAD

**Issue by jooyoungseo** [rnuske/komaletter#9] opened 2019-11-22 21:11 UTC
Currently, `komaletter::komaletter()` output cannot be rendered on Windows platform.

Please refer to the following reproducible code:

``` r
test <- rmarkdown::draft(file = 'test', 
  template =   'pdf', 
  package = 'komaletter', 
  create_dir = FALSE, 
  edit = FALSE
)

rmarkdown::render(test, output_format = 'komaletter::komaletter')
#> processing file: test.Rmd
#> output file: test.knit.md
#> "C:/PROGRA~3/CHOCOL~1/bin/pandoc" +RTS -K512m -RTS test.utf8.md --to latex --from markdown+tex_math_single_backslash-autolink_bare_uris --output test.tex --template "C:\PROGRA~1\R\R-36~1.1\library\KOMALE~1\RMARKD~1\TEMPLA~1\pdf\RESOUR~1\template.tex" --highlight-style tango --pdf-engine pdflatex --lua-filter "C:/Program Files/R/R-3.6.1/library/rmarkdown/rmd/lua/pagebreak.lua" --lua-filter "C:/Program Files/R/R-3.6.1/library/rmarkdown/rmd/lua/latex-div.lua" "--variable=lco_default:C:/Program Files/R/R-3.6.1/library/komaletter/rmarkdown/templates/pdf/resources/maintainersDelight"
#> ! LaTeX Error: Missing \begin{document}.
#> Error: Failed to compile test.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See test.log for more info.
```

<sup>Created on 2019-11-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2019-11-22                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source                            
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.1)                    
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                    
#>  cli           1.1.0      2019-03-19 [1] CRAN (R 3.6.1)                    
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.1)                    
#>  digest        0.6.22     2019-10-21 [1] CRAN (R 3.6.1)                    
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.1)                    
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.1)                    
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.1)                    
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)                    
#>  knitr         1.26.1     2019-11-19 [1] Github (yihui/knitr@3c89ab1)      
#>  komaletter    0.3.1.9000 2019-11-18 [1] Github (rnuske/komaletter@8b0cfa3)
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.1)                    
#>  pillar        1.4.2      2019-06-29 [1] CRAN (R 3.6.1)                    
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 3.6.1)                    
#>  purrr         0.3.3      2019-10-18 [1] CRAN (R 3.6.1)                    
#>  Rcpp          1.0.3      2019-11-08 [1] CRAN (R 3.6.1)                    
#>  reprex        0.3.0.9001 2019-11-13 [1] Github (tidyverse/reprex@27aa69a) 
#>  rlang         0.4.2      2019-11-22 [1] Github (r-lib/rlang@dbcb76f)      
#>  rmarkdown     1.17.4     2019-11-21 [1] Github (rstudio/rmarkdown@1e0964c)
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.1)                    
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                    
#>  stringr       1.4.0.9000 2019-11-11 [1] Github (hadley/stringr@80aaaac)   
#>  styler        1.2.0.9000 2019-11-13 [1] Github (r-lib/styler@a8acde5)     
#>  tibble        2.1.3      2019-06-06 [1] CRAN (R 3.6.1)                    
#>  tinytex       0.17.1     2019-11-18 [1] Github (yihui/tinytex@4a251b5)    
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.1)                    
#>  xfun          0.11.3     2019-11-22 [1] Github (yihui/xfun@4fcd6ff)       
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.6.0)                    
#> 
#> [1] C:/Program Files/R/R-3.6.1/library
```

</details>

**Comment by rnuske** [comment] 2019-11-28 11:34
I do not work on windows. So I had trouble to reproduce your error. Approaching the error I looked at the AppVeyor builds of this package, CRAN's winbuilder output and tests on colleagues windows computers.

* AppVeyor was not helpful because no PDFs are compiled. Building reference manual and vignettes is turned off.
* Windows on CRAN builds the vignettes just fine and most of the vignettes are basically just letters. Thus, there are windows systems where komaletter works alright. 
* compiling Rmd to PDF on my colleagues computers had problems unrelated to komaletter. So it is not easy to get rmarkdown to work with LaTeX on windows.

In a first step I would like to know whether you can compile a simple Rmd to PDF by just using `rmarkdown`. For instance:
```
md <- '---\ntitle: "Untitled"\noutput: pdf_document\n---\n\n## R Markdown\n\nThis is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents.\n\nWhen you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code such as `r 1+1` within the document.\n'

writeLines(text=md, con='example.Rmd')

rmarkdown::render('example.Rmd')
```

And whether the TeX-package [`koma-script`](https://www.ctan.org/pkg/koma-script) is available on your computer.

**Comment by rnuske** [comment] 2019-12-03 11:05
I was now able to run your code on a windowsmachine  with a correctly configured MiKTeX and could not reproduce your error. The commands produced the expected PDF.

If you have no further clues how to reproduce the error, I would tend to close the issue.

**Comment by rnuske** [comment] 2019-12-07 13:29
The issues [3 in resume](https://github.com/JacekPardyak/resume/issues/3) and [259 in rticles](https://github.com/rstudio/rticles/issues/259) look similar and could not be replicated either.

**Closed by rnuske** 2019-12-07 13:29 UTC
